// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { supabase } from "./client";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" })
  .client(async ({ next }) => {
    let token = "";
    if (typeof window !== "undefined") {
      try {
        const { data } = await supabase.auth.getSession();
        let session = data.session;
        if (!session) {
          const res = await supabase.auth.signInAnonymously();
          session = res.data.session;
        }
        token = session?.access_token ?? "";
      } catch (err) {
        console.warn("Could not acquire Supabase anonymous session:", err);
      }
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  })
  .server(async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();
    const authHeader = request?.headers?.get("authorization");
    let token = authHeader?.startsWith("Bearer ") ? authHeader.replace("Bearer ", "") : undefined;
    let sub = "";
    let claims: Record<string, unknown> = {};
    let supabaseClient: ReturnType<typeof createClient<Database>> | undefined;

    if (token && token.split(".").length === 3) {
      const sb = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      });

      const { data, error } = await sb.auth.getClaims(token);
      if (!error && data?.claims?.sub) {
        sub = data.claims.sub;
        claims = data.claims as Record<string, unknown>;
        supabaseClient = sb;
      }
    }

    if (!sub) {
      // Auto-provision an anonymous session so the server function always has an isolated owner
      const tempSb = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
      });
      const { data: anonData, error: anonErr } = await tempSb.auth.signInAnonymously();
      if (!anonErr && anonData.user) {
        sub = anonData.user.id;
        token = anonData.session?.access_token;
        supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
            headers: token ? { Authorization: `Bearer ${token}` } : {},
          },
          auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
        });
      } else {
        throw new Error("Unauthorized: Could not establish session");
      }
    }

    return next({
      context: {
        supabase: supabaseClient,
        userId: sub,
        claims,
      },
    });
  });
