// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { supabase } from "./client";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" })
  .client(async ({ next }) => {
    let token = "";
    if (typeof window !== "undefined") {
      try {
        const { data } = await supabase.auth.getSession();
        let session = data.session;
        if (!session) {
          const res = await supabase.auth.signInAnonymously();
          session = res.data.session;
        }
        token = session?.access_token ?? "";
      } catch (err) {
        console.warn("Could not acquire Supabase anonymous session:", err);
      }
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  })
  .server(async ({ next }) => {
    const DEFAULT_URL = "https://wrfnaxpnidnvamlvjnet.supabase.co";
    const DEFAULT_KEY =
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZm5heHBuaWRudmFtbHZqbmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA5MzUyMTgsImV4cCI6MjEwNjUxMTIxOH0.We43uw_oJoW3LZW2tUwkcpfZ-dk0wHwsKAWZrBT76I4";

    const SUPABASE_URL = process.env["SUPABASE_URL"] || DEFAULT_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"] || DEFAULT_KEY;

    const request = getRequest();
    const authHeader = request?.headers?.get("authorization");
    let token = authHeader?.startsWith("Bearer ") ? authHeader.replace("Bearer ", "") : undefined;
    let sub = "";
    let claims: Record<string, unknown> = {};
    let supabaseClient: ReturnType<typeof createClient<Database>> | undefined;

    if (token && token.split(".").length === 3) {
      try {
        const sb = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        });

        const { data, error } = await sb.auth.getClaims(token);
        if (!error && data?.claims?.sub) {
          sub = data.claims.sub;
          claims = data.claims as Record<string, unknown>;
          supabaseClient = sb;
        }
      } catch {
        // Fall back to server anonymous session
      }
    }

    if (!sub) {
      try {
        const tempSb = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
          auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
        });
        const { data: anonData, error: anonErr } = await tempSb.auth.signInAnonymously();
        if (!anonErr && anonData.user) {
          sub = anonData.user.id;
          token = anonData.session?.access_token;
          supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
            global: {
              fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
              headers: token ? { Authorization: `Bearer ${token}` } : {},
            },
            auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
          });
        }
      } catch {
        // network issue fallback
      }

      if (!sub) {
        sub = crypto.randomUUID();
        supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          },
          auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
        });
      }
    }

    return next({
      context: {
        supabase: supabaseClient,
        userId: sub,
        claims,
      },
    });
  });
